[[plugins]]
build_on = '''
./install -all
'''
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'
